"""
Stage 2: Student Response Generation (Student LLM)
Simulates student responses to MP indicators based on their problem-solving process.
"""
import asyncio
import json
import os
from openai import AsyncOpenAI
from typing import List, Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv()

# Initialize OpenAI client
client = AsyncOpenAI(
    api_key=os.getenv("OPENAI_API_KEY", ""),
)

PROMPT = """You are Student GPT.
Inputs:
1. A math problem statement.
2. A set of indicators generated by Teacher GPT.
3. A student's written solution attempt (from OCR).

Your role:
- Reconstruct the student's *apparent reasoning and assumptions* based on written actions and tightly justified inferences.
- You are NOT:
    - correcting, evaluating, completing, or improving the solution,
    - inventing reasoning or resolve ambiguity.

Reconstruction rules
For each indicator, write EXACTLY ONE of the following:

1. If the student clearly wrote relevant content:
   - Begin with: "The student explicitly writes that ..."

2. If the student did not write it explicitly, but their immediate written actions
   strongly indicate it:
   - Begin with: "Although not explicitly written, the student's next written step shows that ..."

   This is allowed ONLY when the inference is:
   - unavoidable,
   - local,
   - directly supported by a visible written action.

3. If there is insufficient evidence:
   - Write exactly: "I don't know."

ABSOLUTE PROHIBITIONS
- NEVER replace a wrong answer with a correct one.
- NEVER guess.
- If the solution stops, reflect the incompleteness.

**Output format**
Return your answers as a dictionary where
- Your output MUST be valid JSON.
- Keys are the indicator codes (e.g., "CU1", "SC2", "PF3", "AR1").
- Each value reflects ONLY what can be supported by the student's written solution.

Output:
{
    "CU1": "...",
    "SC1": "...",
    "CU2": "...",
    ...
}


---

### One-shot Example

Input Indicators:
{
    "CU1": "Determine the type and order of this equation",
    "SC1": "Rewrite the equation in a simpler form",
    "AD1": "Identify the conditions required to solve the equation",
    "PF1": "Compute the values that satisfy the conditions",
    "SC2": "Find the smaller value between the values found above."
}

Question (In Korean): Find the smallest value(s) of y that make the following expression equal to 0.
                      y^2 + 3y + 2

My solving process (OCR):
    `y^2 + 3y' + 2y = 0`
    `(r+1)(r+2)`

My answer: [{"index":0,"answers":[{"type":"integer","value":-2}]}]

Output:
{
    "CU1": "Implicit but strongly evidenced by written actions: This is a quadratic equation.",
    "SC1": "Explicitly written: Rewrite the characteristic polynomial as (r+1)(r+2).",
    "AD1": "Implicit but strongly evidenced by written actions: If one of the multiplied factors is zero, the result becomes zero.",
    "PF1": "Implicit but strongly evidenced by written actions: The values that satisfy the condition are -1 and -2.",
    "SC2": "Implicit but strongly evidenced by written actions: Select -2, because it is smaller than -1"
}
-----------------------------------------------------------------------------------
"""


def read_json_file(file_path: str, encoding: str = "utf-8") -> List[Dict[str, Any]]:
    with open(file_path, 'r', encoding=encoding) as file:
        return json.load(file)


def save_json_file(data: List[Dict[str, Any]], file_path: str, encoding: str = "utf-8"):
    with open(file_path, 'w', encoding=encoding) as file:
        json.dump(data, file, ensure_ascii=False, indent=4)


async def call_gpt_api(item: Dict[str, Any], model_name: str) -> Optional[Dict[str, int]]:
    MAX_TRIAL = 5
    for trial in range(MAX_TRIAL):
        try:
            problem = item.get("problem_text", "")
            mathematical_proficiency_indicators = item.get("mathematical_proficiency_indicators", "")

            if isinstance(mathematical_proficiency_indicators, dict):
                indicator_items = list(mathematical_proficiency_indicators.items())
            elif isinstance(mathematical_proficiency_indicators, list):
                indicator_items = []
                for d in mathematical_proficiency_indicators:
                    if isinstance(d, dict):
                        indicator_items.extend(d.items())
            else:
                indicator_items = []

            indicator_text = "[\n"
            for k, v in indicator_items:
                indicator_text += f'    {{ "{k}": "{v}" }},\n'
            indicator_text = indicator_text.rstrip(",\n") + "\n]"

            problem_options = item.get("problem_option", "")
            problem_option_string = f"Options: {problem_options}" if problem_options != "" else ""

            student_solving_trace = item.get("problem_solving_process", "")
            student_answer_set = item.get("student_answer_set", "")
            result = item.get("result", "")

            user_message = f"{PROMPT}\n\nInput Indicators: \n{indicator_text}\n\nProblem (in Korean): {problem}\n{problem_option_string}\n\nMy solving process (OCR):\n{student_solving_trace} \nMy answer: {student_answer_set}\nCorrectness:{result}"

            messages = [
                {"role": "user", "content": user_message}
            ]

            response = await client.chat.completions.create(
                model=model_name,
                messages=messages
            )

            result_text = response.choices[0].message.content

            try:
                result_text = result_text.replace("\\,", ",")
                result_text = result_text.replace("\\", "\\\\")
                result_text = result_text.replace("\\\\\\\\", "\\\\")
                result_text = result_text.replace('\\\\"', '\\"')
                result_dict = json.loads(result_text)
                return result_dict
            except json.JSONDecodeError:
                print(result_text)
                print("JSON DECODING ERROR")

        except Exception as e:
            print(f"Error processing item: {e}")
            return None


async def process_item(idx: int, item: Dict[str, Any], model_name: str) -> Dict[str, Any]:
    if idx % 100 == 0:
        print("idx:", idx)

    result = await call_gpt_api(item, model_name)

    item_copy = item.copy()
    item_copy["answer_indicate"] = result

    return item_copy


async def process_batch_concurrent(batch: List[Dict[str, Any]], concurrent_limit: int, model_name: str) -> List[Dict[str, Any]]:
    """Process items in batches"""
    semaphore = asyncio.Semaphore(concurrent_limit)

    async def process_with_semaphore(idx: int, item: Dict[str, Any]) -> Dict[str, Any]:
        async with semaphore:
            return await process_item(idx, item, model_name)

    tasks = [process_with_semaphore(idx, item) for idx, item in enumerate(batch)]
    results = await asyncio.gather(*tasks)

    return results


async def main():
    # File paths - modify these for your setup
    encoding = "utf-8"
    json_file_path = "data/1_indicator.json"  # Input: data with MP indicators
    output_json_file_path = "data/2_student_answer.json"  # Output: data with student responses

    # Model name
    model_name = "gpt-4o"

    # Batch settings
    BATCH_SIZE = 100
    concurrent_limit = 100

    # Read input data
    data = read_json_file(json_file_path, encoding)
    print(f"Total records: {len(data)}")

    # Load existing results if available
    if os.path.exists(output_json_file_path):
        processed_data = read_json_file(output_json_file_path, encoding)
        print(f"Loaded existing results: {len(processed_data)} records")
    else:
        processed_data = []
        for item in data:
            item_copy = item.copy()
            item_copy["answer_indicate"] = None
            processed_data.append(item_copy)
        save_json_file(processed_data, output_json_file_path, encoding)
        print(f"Initialized output file with {len(processed_data)} records")

    # Find pending items
    pending_indices = [i for i, item in enumerate(processed_data) if item.get("answer_indicate") is None]
    print(f"Pending items: {len(pending_indices)}")

    if len(pending_indices) == 0:
        print("No pending items to process!")
        return

    # Process in batches
    total_batches = (len(pending_indices) + BATCH_SIZE - 1) // BATCH_SIZE

    for batch_num in range(total_batches):
        start_idx = batch_num * BATCH_SIZE
        end_idx = min(start_idx + BATCH_SIZE, len(pending_indices))
        batch_indices = pending_indices[start_idx:end_idx]

        print(f"\nProcessing batch {batch_num + 1}/{total_batches} (items {start_idx + 1}-{end_idx})")

        batch_items = [processed_data[i] for i in batch_indices]

        batch_results = await process_batch_concurrent(
            batch=batch_items,
            concurrent_limit=concurrent_limit,
            model_name=model_name
        )

        for i, result in zip(batch_indices, batch_results):
            processed_data[i] = result

        save_json_file(processed_data, output_json_file_path, encoding)

        success_count = sum(1 for item in processed_data if item.get("answer_indicate") is not None)
        print(f"Saved! Progress: {success_count}/{len(processed_data)} completed")

    print(f"\nAll batches completed! Saved to {output_json_file_path}")

    success_count = sum(1 for item in processed_data if item.get("answer_indicate") is not None)
    fail_count = len(processed_data) - success_count
    print(f"Final Statistics: {success_count} succeeded, {fail_count} failed")


if __name__ == "__main__":
    asyncio.run(main())
